# Generated by Django 5.2.6 on 2026-03-01 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryname', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyname', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('partyname', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('add1', models.CharField(blank=True, max_length=255, null=True)),
                ('add2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('openingdr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('openingcr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemname', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('opening_stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sale_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('purchase_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('reorder', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.category')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.company')),
            ],
        ),
    ]
