# Generated by Django 5.2.6 on 2026-03-01 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('entry_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('party_name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('remark', models.TextField(blank=True, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.party')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseMaster',
            fields=[
                ('invno', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('invdate', models.DateField()),
                ('partyname', models.CharField(blank=True, max_length=255, null=True)),
                ('add1', models.CharField(blank=True, max_length=255, null=True)),
                ('add2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discount_per', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('discount_amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('adjustment', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount_in_words', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.party')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('itemamt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('itemremark', models.CharField(blank=True, max_length=255, null=True)),
                ('itemname', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.item')),
                ('invno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='transactions.purchasemaster')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('entry_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('party_name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('remark', models.TextField(blank=True, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.party')),
            ],
        ),
        migrations.CreateModel(
            name='SaleMaster',
            fields=[
                ('invno', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('invdate', models.DateField()),
                ('partyname', models.CharField(blank=True, max_length=255, null=True)),
                ('add1', models.CharField(blank=True, max_length=255, null=True)),
                ('add2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discount_per', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('discount_amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('adjustment', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount_in_words', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.party')),
            ],
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('itemamt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('itemremark', models.CharField(blank=True, max_length=255, null=True)),
                ('itemname', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.item')),
                ('invno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='transactions.salemaster')),
            ],
        ),
    ]
